# Generated by Django 3.1.3 on 2020-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('Sa', 'Saturday'), ('SU', 'Sunday')], default='M', max_length=2, verbose_name='Day')),
                ('start', models.TimeField(default='09:00', verbose_name='Entry')),
                ('end', models.TimeField(default='17:00', verbose_name='Finish')),
            ],
            options={
                'verbose_name': 'Workshift',
                'verbose_name_plural': 'Workshifts',
            },
        ),
        migrations.CreateModel(
            name='Workhours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
                ('workshift', models.ManyToManyField(related_name='workhours', to='workhours.Workshift')),
            ],
            options={
                'verbose_name': 'Workhour',
                'verbose_name_plural': 'Workhours',
            },
        ),
    ]
