# Generated by Django 3.1.3 on 2020-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2, verbose_name='Day'),
        ),
    ]
