# Generated by Django 3.1.3 on 2020-11-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0002_auto_20201111_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhours',
            name='workshift',
        ),
        migrations.AddField(
            model_name='workhours',
            name='day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='workhours',
            name='end',
            field=models.TimeField(default='17:00', verbose_name='Finish'),
        ),
        migrations.AddField(
            model_name='workhours',
            name='start',
            field=models.TimeField(default='09:00', verbose_name='Entry'),
        ),
        migrations.DeleteModel(
            name='Workshift',
        ),
    ]
